### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by thalesbsfr** [shalini1194/RKT#2]
Hello shalini,

The URL in README that you put the dataset used, is different from the dataset used in the code.Where I find those files?  '../../PEBG-master/ednet/ednet.npz',  '../../KT-GAT/ednet_corr', and  ../../PEBGmaster/ednet/pro_pro_sparse.npz'

**Comment by skewondr** [comment]
You can find those files at (https://github.com/lyf-1/PEBG).
However, even if you find those files, you may not run 'trian_rkt.py'.
Because there is more empty code in there.

**Comment by shalini1194** [comment]
Thedata files can be found here: https://drive.google.com/drive/folders/1LRljqWfODwTYRMPw6wEJ_mMt1KZ4xBDk.
