### ISSUE TITLE
Clarification on RAM usage

### ISSUE THREAD

**Issue by SimoneSartoni** [shalini1194/RKT#3]
Hello Shalini,
I am trying to run this code using Kaggle platform, which allows only 13 GB of RAM, in "Prepare_Batches" function RAM has already reached this limit.
I am considering different solutions (as subscribing to Colab Pro), but I would need to know approximately how much RAM I need.
Thank you in advance for the information.

**Comment by shalini1194** [comment]
The code should run on 32GB RAM.
